-- Synchronize the production booking lookup tables with the current public website data.
-- This is required so every valid online inquiry can resolve its routed staff and service IDs.

insert into public.service_categories (slug, name, accent, description)
values
  ('nails', 'Nails', '#F06BD6', 'Bright acrylics, gel, fills, sculpted art, and detail-heavy sets from nail artists who live for color.'),
  ('hair', 'Hair', '#FFE45C', 'From polished salon services to bold color work, hair bookings route to stylists only.'),
  ('tattoo', 'Tattoo', '#4DDCE5', 'Tattoo inquiries show tattoo staff only, with portfolios and consultation-first booking flows.'),
  ('aesthetics', 'Aesthetics & Spa', '#A95CFF', 'Aesthetics and spa services connect visitors with the right licensed beauty professionals.')
on conflict (slug) do update set name=excluded.name, accent=excluded.accent, description=excluded.description;

insert into public.services (category_id, slug, name, description, duration_minutes, price_label)
values
  ((select id from public.service_categories where slug='nails'), 'acrylic-full-set', 'Acrylic Full Set', 'Full acrylic set. Gel polish is included at no extra cost.', 90, '$60'),
  ((select id from public.service_categories where slug='nails'), 'acrylic-fill-in', 'Acrylic Fill-In', 'Acrylic fill-in service. Gel polish is included at no extra cost.', 75, '$50'),
  ((select id from public.service_categories where slug='nails'), 'poly-gel-full-set', 'Poly-Gel Full Set', 'Poly-gel full set. Gel polish is included at no extra cost.', 90, '$70'),
  ((select id from public.service_categories where slug='nails'), 'poly-gel-fill-in', 'Poly-Gel Fill-In', 'Poly-gel fill-in service. Gel polish is included at no extra cost.', 75, '$60'),
  ((select id from public.service_categories where slug='nails'), 'gel-full-set', 'Gel Full Set', 'Gel full set with gel polish included at no extra cost.', 90, '$70'),
  ((select id from public.service_categories where slug='nails'), 'gel-fill-in', 'Gel Fill-In', 'Gel fill-in service with gel polish included at no extra cost.', 75, '$60'),
  ((select id from public.service_categories where slug='nails'), 'dip-powder', 'Dip Powder', 'Dip powder nail service with gel polish included at no extra cost.', 75, '$60'),
  ((select id from public.service_categories where slug='nails'), 'dip-with-tips', 'Dip With Tips', 'Dip powder with tips. Gel polish is included at no extra cost.', 90, '$65'),
  ((select id from public.service_categories where slug='nails'), 'manicure', 'Manicure', 'Natural nail manicure. Kids 10 and under can receive any natural nail service for $10 off.', 45, '$30'),
  ((select id from public.service_categories where slug='nails'), 'deluxe-manicure', 'Deluxe Manicure', 'Deluxe manicure service. Kids 10 and under can receive any natural nail service for $10 off.', 60, '$50'),
  ((select id from public.service_categories where slug='nails'), 'deluxe-pedicure', 'Deluxe Pedicure', 'A full pedicure with toe trimming, cuticle and callus removal, lotion massage, sugar scrub, hot towel, and gel polish.', 60, '$50'),
  ((select id from public.service_categories where slug='nails'), 'jelly-pedicure', 'Jelly Pedicure', 'A full pedicure with warm jelly soak, hydrating jelly massage, sugar scrub, lotion massage, hot towel, and gel polish.', 75, '$65'),
  ((select id from public.service_categories where slug='nails'), 'royal-pedicure', 'Royal Pedicure', 'A full pedicure with soak, mask, sugar scrub, lotion massage, hot towel, and gel polish.', 80, '$70'),
  ((select id from public.service_categories where slug='nails'), 'ultimate-pedicure', 'Ultimate Pedicure', 'A full pedicure with soak, mask, sugar scrub, lotion massage, callus softener, hot towel, deep moisturizing treatment, hot stones, and gel polish.', 90, '$80'),
  ((select id from public.service_categories where slug='nails'), 'kids-regular-polish', 'Kids Regular Polish Add-On', 'Children under 10 can get regular polish free with an adult service.', 15, 'Free with adult service'),
  ((select id from public.service_categories where slug='hair'), 'cut-with-wash', 'Cut With Wash', 'Haircut with wash.', 45, '$35'),
  ((select id from public.service_categories where slug='hair'), 'cut-without-wash', 'Cut Without Wash', 'Haircut without wash.', 30, '$20'),
  ((select id from public.service_categories where slug='hair'), 'buzz-cut', 'Buzz Cut', 'Buzz cut service.', 20, '$10'),
  ((select id from public.service_categories where slug='hair'), 'bang-trim', 'Bang Trim', 'Bang trim service.', 15, '$5'),
  ((select id from public.service_categories where slug='hair'), 'conditioning-treatment', 'Conditioning Treatment', 'Hair care treatment for extra conditioning and softness.', 30, '$20'),
  ((select id from public.service_categories where slug='hair'), 'roller-set', 'Roller Set', 'Roller set styling service.', 60, '$45'),
  ((select id from public.service_categories where slug='hair'), 'blowout', 'Blowout', 'Blowout service, wash included.', 60, '$40'),
  ((select id from public.service_categories where slug='hair'), 'style', 'Style', 'Finished style service.', 60, '$40'),
  ((select id from public.service_categories where slug='hair'), 'updo', 'Updo', 'Updo styling service.', 75, '$60'),
  ((select id from public.service_categories where slug='hair'), 'spiral-perm', 'Spiral Perm', 'Chemical or color service; final pricing may vary by hair and appointment needs.', 180, '$80+'),
  ((select id from public.service_categories where slug='hair'), 'partial-perm', 'Partial Perm', 'Partial perm service.', 120, '$50'),
  ((select id from public.service_categories where slug='hair'), 'full-color', 'Full Color', 'Full color service; final pricing may vary by hair and appointment needs.', 150, '$80+'),
  ((select id from public.service_categories where slug='hair'), 'full-highlights', 'Full Highlights', 'Full highlight service; final pricing may vary by hair and appointment needs.', 180, '$120+'),
  ((select id from public.service_categories where slug='hair'), 'balayage', 'Balayage', 'Balayage color service; final pricing may vary by hair and appointment needs.', 210, '$200+'),
  ((select id from public.service_categories where slug='hair'), 'money-piece', 'Money Piece', 'Money piece color service; final pricing may vary by hair and appointment needs.', 90, '$40+'),
  ((select id from public.service_categories where slug='hair'), 'partial-color', 'Partial Color', 'Partial color service; final pricing may vary by hair and appointment needs.', 120, '$50+'),
  ((select id from public.service_categories where slug='hair'), 'partial-highlights', 'Partial Highlights', 'Partial highlight service; final pricing may vary by hair and appointment needs.', 120, '$75+'),
  ((select id from public.service_categories where slug='hair'), 'root-touch-up', 'Root Touch Up', 'Root touch up service; final pricing may vary by hair and appointment needs.', 90, '$60+'),
  ((select id from public.service_categories where slug='tattoo'), 'tattoo-consult', 'Tattoo Consultation', 'Start with a tattoo consultation so the artist can review the idea, placement, timing, and pricing with you.', 30, 'Consult first'),
  ((select id from public.service_categories where slug='tattoo'), 'flash-tattoo', 'Flash Tattoo', 'Flash tattoo requests are reviewed by the artist so availability, sizing, placement, and pricing are clear before the appointment.', 120, 'Quoted by artist'),
  ((select id from public.service_categories where slug='aesthetics'), 'thirty-minute-facial', '30 Min Facial', 'A mini facial starting with cleansing, exfoliation, toner, and moisturizer.', 30, '$40.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'back-facial', 'Back Facial', 'A relaxing back facial that includes hot stones, double cleansing, extraction, exfoliation, massage, and more.', 60, '$60.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'sixty-minute-facial', '60 Min Facial', 'A relaxing facial that includes double cleansing, extraction, exfoliation, massage, and more.', 60, '$60.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'dermaplaning', 'Dermaplaning', 'Exfoliates the skin''s epidermis by removing dead skin cells and fine hairs.', 45, '$75.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'hot-stone-massage', 'Hot Stone Massage', 'One-hour hot stone massage.', 60, '$70.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'full-leg-wax', 'Full Leg Wax', 'Full leg waxing service.', 45, '$40.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'brazilian-wax', 'Brazilian Wax', 'Brazilian waxing service.', 45, '$50.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'underarm-wax', 'Underarm Wax', 'Underarm waxing service.', 20, '$20.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'half-arm-wax', 'Half Arm Wax', 'Half arm waxing service.', 30, '$25.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'lip-chin-wax', 'Lip/Chin Wax', 'Lip or chin waxing service.', 15, '$10.00'),
  ((select id from public.service_categories where slug='aesthetics'), 'brow-wax-shape', 'Brow Wax & Shape', 'Brow wax and shape service.', 20, '$20'),
  ((select id from public.service_categories where slug='aesthetics'), 'brow-wax-tint', 'Brow Wax & Tint', 'Brow wax and tint service.', 30, '$30'),
  ((select id from public.service_categories where slug='aesthetics'), 'brow-wax-lami', 'Brow Wax & Lami', 'Brow wax and lamination service.', 45, '$50'),
  ((select id from public.service_categories where slug='aesthetics'), 'brow-wax-lami-tint', 'Brow Wax, Lami, & Tint', 'Brow wax, lamination, and tint service.', 60, '$65'),
  ((select id from public.service_categories where slug='aesthetics'), 'lash-lift-tint', 'Lash Lift & Tint', 'Lash lift and tint service.', 60, '$60'),
  ((select id from public.service_categories where slug='aesthetics'), 'lash-lift', 'Lash Lift', 'Lash lift service.', 45, '$50'),
  ((select id from public.service_categories where slug='aesthetics'), 'classic-lash-set', 'Classic Set', 'Classic lash extension set.', 120, '$70'),
  ((select id from public.service_categories where slug='aesthetics'), 'mixed-lash-set', 'Mixed Set', 'Mixed lash extension set.', 150, '$80'),
  ((select id from public.service_categories where slug='aesthetics'), 'volume-lash-set', 'Volume Set', 'Volume lash extension set.', 180, '$100'),
  ((select id from public.service_categories where slug='aesthetics'), 'air-brushed-brow-add-on', 'Air Brushed Brow Add-On', 'Add air brushed brow to any tint service.', 15, '+$10')
on conflict (slug) do update set category_id=excluded.category_id, name=excluded.name, description=excluded.description, duration_minutes=excluded.duration_minutes, price_label=excluded.price_label;

insert into public.staff_members (slug, name, title, bio, photo_url, role, calendar_color)
values
  ('team-member-01', 'Annika', 'Nail Artist', 'This nail artist offers color-forward sets, detailed nail art, and appointment options for guests who want a look that fits their style.', '/staff/team-member-01.jpg', 'staff', '#F06BD6'),
  ('team-member-02', 'Juny', 'Nail Artist', 'Hi I’m Juny! I was recently licensed in February and just graduated. I am an 18-year-old nail tech who is just in the beginning stages but a fast learner. I enjoy doing nails and hair, as those are my specialty skills and what I love to do. I plan on getting licensed for cosmetology to further my education in the beauty industry.', '/staff/team-member-02.jpg', 'staff', '#FF3131'),
  ('team-member-03', 'Seven', 'Tattoo Artist', 'This tattoo artist is available for consultation-first projects, flash ideas, placement planning, and portfolio review.', '/staff/team-member-03.jpg', 'staff', '#4DDCE5'),
  ('team-member-04', 'Akira', 'Aesthetics & Spa Specialist', 'This beauty specialist supports spa, skincare, brow, lash, and self-care services with a calm client-first approach.', '/staff/team-member-04.jpg', 'staff', '#A95CFF'),
  ('team-member-05', 'Lia', 'Nail Artist', 'Hi! My name is Lia and I have been a licensed nail tech for almost 2 years. I love doing animal print, alternative, and Y2K designs. I’m a huge Hello Kitty lover and I love anime!', '/staff/team-member-05.jpg', 'staff', '#FF8BE8'),
  ('team-member-06', 'Serenity', 'Nail Artist', 'Hi! My name is Serenity, and I’m a nail tech at Mild2Wild. I attended the spa tech program at LCJVS during high school, and I’ve been licensed for about a year now. I absolutely love doing nail art — it’s definitely my favorite part of the job. I also really enjoy getting to know my clients and creating a fun, comfortable experience while they’re in my chair. My favorite colors are pink and burgundy, and outside of work I love spending time outdoors, enjoying the sunshine, and hanging out with my friends and family. I’m also obsessed with my dog, Twink, who’s a very spoiled chiweenie and basically my baby.', '/staff/team-member-06.jpg', 'staff', '#B73CFF'),
  ('team-member-07', 'Von', 'Tattoo Artist', 'This tattoo artist is available for consultation-first projects, flash ideas, placement planning, and portfolio review.', '/staff/team-member-07.jpg', 'staff', '#30F2FF'),
  ('team-member-08', 'Veronica', 'Hair Stylist', 'This stylist helps guests plan cuts, color, transformations, and finishing details that match their look and routine.', '/staff/team-member-08.jpg', 'staff', '#FFE45C'),
  ('team-member-09', 'Laylay', 'Hair Stylist', 'This stylist helps guests plan cuts, color, transformations, and finishing details that match their look and routine.', '/staff/team-member-09.jpg', 'staff', '#FFB84D'),
  ('team-member-10', 'Surge', 'Tattoo Artist', 'I’m Surge, I’ve been an artist for as long as I can remember, and I’ve always loved bringing people’s ideas to life. Realism and capturing the small details others overlook have always been my passion. Throughout my life, people constantly told me I should do something with my art, but I never knew what that would be. I spent years working in factories and warehouses until a serious work injury changed everything. A herniated disc left me unable to do the heavy lifting and physical work I relied on to provide for my family. It was devastating, and I felt lost. While working as a waiter, several coworkers encouraged me to apply for a tattoo apprenticeship. Looking back, it felt like life was pushing me toward the path I was meant to take. Art had always been there — I just needed the push to pursue it. Today, tattooing allows me to combine my love for art with my passion for helping people. Whether it’s creating meaningful memorial pieces, covering scars, designing something unique, or simply helping someone feel more confident, I take pride in making every tattoo personal. For me, tattooing isn’t just artwork — it’s a way to connect with people and make a positive impact in their lives.', '/staff/team-member-10.jpg', 'staff', '#E23B16'),
  ('team-member-11', 'Yoyo', 'Hair Stylist', 'This stylist helps guests plan cuts, color, transformations, and finishing details that match their look and routine.', '/staff/team-member-11.jpg', 'staff', '#E9FF63'),
  ('team-member-12', 'Schwebels', 'Mascot', 'Schwebels is the Mild 2 Wild shop dog and official mascot — part of the studio personality, welcome energy, and brand moments without appearing as a bookable service provider.', '/staff/team-member-12.jpg', 'staff', '#4DDCE5'),
  ('team-member-13', 'Caitlin', 'Nail Artist', 'This nail artist offers color-forward sets, detailed nail art, and appointment options for guests who want a look that fits their style.', '/staff/team-member-13.jpg', 'owner', '#FF7AC8'),
  ('team-member-14', 'Nani', 'Nail Artist', 'This nail artist offers color-forward sets, detailed nail art, and appointment options for guests who want a look that fits their style.', '/staff/team-member-14.jpg', 'staff', '#F06BD6'),
  ('team-member-15', 'Anahi', 'Nail Artist', 'This nail artist offers color-forward sets, detailed nail art, and appointment options for guests who want a look that fits their style.', '/staff/team-member-15.jpg', 'staff', '#FF5AB8'),
  ('team-member-16', 'Zaylin', 'Nail Artist', 'This nail artist offers color-forward sets, detailed nail art, and appointment options for guests who want a look that fits their style.', '/staff/team-member-16.jpg', 'staff', '#FF8BE8'),
  ('team-member-17', 'Piper', 'Nail Artist', 'Hi, I’m Piper. I like anime and Hello Kitty, and I specialize in almond shape nails. I do Gel-X, acrylic, and manicures.', '/staff/team-member-17.jpg', 'staff', '#B73CFF'),
  ('team-member-18', 'Sharvelle', 'Hair Stylist', 'Sharvelle is part of the Mild 2 Wild hair team, helping guests plan cuts, color, styling, and transformation appointments that fit their look and routine.', '/staff/team-member-18.jpg', 'staff', '#FF4FB3'),
  ('team-member-19', 'Mari', 'Tattoo Artist', 'Mari is a tattoo artist at Mild 2 Wild. Guests can use her profile for consultation-first tattoo requests, flash questions, and appointment planning.', '/staff/team-member-19.jpg', 'staff', '#00C8D8'),
  ('team-member-20', 'Tim', 'Team Member', 'Tim is part of the Mild 2 Wild team. Guests can contact the studio for current details about his availability and services.', '/staff/team-member-20.jpg', 'staff', '#9ADFEA'),
  ('team-member-21', 'Alicia', 'Nail Artist', 'Alicia is a nail artist at Mild 2 Wild. Guests can contact the studio for current details about her availability, nail services, and appointment options.', '/staff/team-member-21.jpg', 'staff', '#FF7AC8')
on conflict (slug) do update set name=excluded.name, title=excluded.title, bio=excluded.bio, photo_url=excluded.photo_url, role=excluded.role, calendar_color=excluded.calendar_color;

insert into public.staff_service_categories (staff_id, category_id)
select staff.id, category.id from (values
  ('team-member-01', 'nails'),
  ('team-member-02', 'nails'),
  ('team-member-03', 'tattoo'),
  ('team-member-04', 'aesthetics'),
  ('team-member-05', 'nails'),
  ('team-member-06', 'nails'),
  ('team-member-07', 'tattoo'),
  ('team-member-08', 'hair'),
  ('team-member-09', 'hair'),
  ('team-member-10', 'tattoo'),
  ('team-member-11', 'hair'),
  ('team-member-13', 'nails'),
  ('team-member-14', 'nails'),
  ('team-member-15', 'nails'),
  ('team-member-16', 'nails'),
  ('team-member-17', 'nails'),
  ('team-member-18', 'hair'),
  ('team-member-19', 'tattoo'),
  ('team-member-21', 'nails')
) as map(staff_slug, category_slug)
join public.staff_members staff on staff.slug=map.staff_slug
join public.service_categories category on category.slug=map.category_slug
on conflict do nothing;

insert into public.staff_services (staff_id, service_id)
select staff.id, service.id from (values
  ('team-member-01', 'acrylic-full-set'),
  ('team-member-01', 'acrylic-fill-in'),
  ('team-member-01', 'poly-gel-full-set'),
  ('team-member-01', 'poly-gel-fill-in'),
  ('team-member-01', 'gel-full-set'),
  ('team-member-01', 'gel-fill-in'),
  ('team-member-01', 'dip-powder'),
  ('team-member-01', 'dip-with-tips'),
  ('team-member-01', 'manicure'),
  ('team-member-01', 'deluxe-manicure'),
  ('team-member-01', 'deluxe-pedicure'),
  ('team-member-01', 'jelly-pedicure'),
  ('team-member-01', 'royal-pedicure'),
  ('team-member-01', 'ultimate-pedicure'),
  ('team-member-01', 'kids-regular-polish'),
  ('team-member-02', 'acrylic-full-set'),
  ('team-member-02', 'acrylic-fill-in'),
  ('team-member-02', 'poly-gel-full-set'),
  ('team-member-02', 'poly-gel-fill-in'),
  ('team-member-02', 'gel-full-set'),
  ('team-member-02', 'gel-fill-in'),
  ('team-member-02', 'dip-powder'),
  ('team-member-02', 'dip-with-tips'),
  ('team-member-02', 'manicure'),
  ('team-member-02', 'deluxe-manicure'),
  ('team-member-02', 'deluxe-pedicure'),
  ('team-member-02', 'jelly-pedicure'),
  ('team-member-02', 'royal-pedicure'),
  ('team-member-02', 'ultimate-pedicure'),
  ('team-member-02', 'kids-regular-polish'),
  ('team-member-03', 'tattoo-consult'),
  ('team-member-03', 'flash-tattoo'),
  ('team-member-04', 'thirty-minute-facial'),
  ('team-member-04', 'back-facial'),
  ('team-member-04', 'sixty-minute-facial'),
  ('team-member-04', 'dermaplaning'),
  ('team-member-04', 'hot-stone-massage'),
  ('team-member-04', 'full-leg-wax'),
  ('team-member-04', 'brazilian-wax'),
  ('team-member-04', 'underarm-wax'),
  ('team-member-04', 'half-arm-wax'),
  ('team-member-04', 'lip-chin-wax'),
  ('team-member-04', 'brow-wax-shape'),
  ('team-member-04', 'brow-wax-tint'),
  ('team-member-04', 'brow-wax-lami'),
  ('team-member-04', 'brow-wax-lami-tint'),
  ('team-member-04', 'lash-lift-tint'),
  ('team-member-04', 'lash-lift'),
  ('team-member-04', 'classic-lash-set'),
  ('team-member-04', 'mixed-lash-set'),
  ('team-member-04', 'volume-lash-set'),
  ('team-member-04', 'air-brushed-brow-add-on'),
  ('team-member-05', 'acrylic-full-set'),
  ('team-member-05', 'acrylic-fill-in'),
  ('team-member-05', 'poly-gel-full-set'),
  ('team-member-05', 'poly-gel-fill-in'),
  ('team-member-05', 'gel-full-set'),
  ('team-member-05', 'gel-fill-in'),
  ('team-member-05', 'dip-powder'),
  ('team-member-05', 'dip-with-tips'),
  ('team-member-05', 'manicure'),
  ('team-member-05', 'deluxe-manicure'),
  ('team-member-05', 'deluxe-pedicure'),
  ('team-member-05', 'jelly-pedicure'),
  ('team-member-05', 'royal-pedicure'),
  ('team-member-05', 'ultimate-pedicure'),
  ('team-member-05', 'kids-regular-polish'),
  ('team-member-06', 'acrylic-full-set'),
  ('team-member-06', 'acrylic-fill-in'),
  ('team-member-06', 'poly-gel-full-set'),
  ('team-member-06', 'poly-gel-fill-in'),
  ('team-member-06', 'gel-full-set'),
  ('team-member-06', 'gel-fill-in'),
  ('team-member-06', 'dip-powder'),
  ('team-member-06', 'dip-with-tips'),
  ('team-member-06', 'manicure'),
  ('team-member-06', 'deluxe-manicure'),
  ('team-member-06', 'deluxe-pedicure'),
  ('team-member-06', 'jelly-pedicure'),
  ('team-member-06', 'royal-pedicure'),
  ('team-member-06', 'ultimate-pedicure'),
  ('team-member-06', 'kids-regular-polish'),
  ('team-member-07', 'tattoo-consult'),
  ('team-member-07', 'flash-tattoo'),
  ('team-member-08', 'cut-with-wash'),
  ('team-member-08', 'cut-without-wash'),
  ('team-member-08', 'buzz-cut'),
  ('team-member-08', 'bang-trim'),
  ('team-member-08', 'conditioning-treatment'),
  ('team-member-08', 'roller-set'),
  ('team-member-08', 'blowout'),
  ('team-member-08', 'style'),
  ('team-member-08', 'updo'),
  ('team-member-08', 'spiral-perm'),
  ('team-member-08', 'partial-perm'),
  ('team-member-08', 'full-color'),
  ('team-member-08', 'full-highlights'),
  ('team-member-08', 'balayage'),
  ('team-member-08', 'money-piece'),
  ('team-member-08', 'partial-color'),
  ('team-member-08', 'partial-highlights'),
  ('team-member-08', 'root-touch-up'),
  ('team-member-09', 'cut-with-wash'),
  ('team-member-09', 'cut-without-wash'),
  ('team-member-09', 'buzz-cut'),
  ('team-member-09', 'bang-trim'),
  ('team-member-09', 'conditioning-treatment'),
  ('team-member-09', 'roller-set'),
  ('team-member-09', 'blowout'),
  ('team-member-09', 'style'),
  ('team-member-09', 'updo'),
  ('team-member-09', 'spiral-perm'),
  ('team-member-09', 'partial-perm'),
  ('team-member-09', 'full-color'),
  ('team-member-09', 'full-highlights'),
  ('team-member-09', 'balayage'),
  ('team-member-09', 'money-piece'),
  ('team-member-09', 'partial-color'),
  ('team-member-09', 'partial-highlights'),
  ('team-member-09', 'root-touch-up'),
  ('team-member-10', 'tattoo-consult'),
  ('team-member-10', 'flash-tattoo'),
  ('team-member-11', 'cut-with-wash'),
  ('team-member-11', 'cut-without-wash'),
  ('team-member-11', 'buzz-cut'),
  ('team-member-11', 'bang-trim'),
  ('team-member-11', 'conditioning-treatment'),
  ('team-member-11', 'roller-set'),
  ('team-member-11', 'blowout'),
  ('team-member-11', 'style'),
  ('team-member-11', 'updo'),
  ('team-member-11', 'spiral-perm'),
  ('team-member-11', 'partial-perm'),
  ('team-member-11', 'full-color'),
  ('team-member-11', 'full-highlights'),
  ('team-member-11', 'balayage'),
  ('team-member-11', 'money-piece'),
  ('team-member-11', 'partial-color'),
  ('team-member-11', 'partial-highlights'),
  ('team-member-11', 'root-touch-up'),
  ('team-member-13', 'acrylic-full-set'),
  ('team-member-13', 'acrylic-fill-in'),
  ('team-member-13', 'poly-gel-full-set'),
  ('team-member-13', 'poly-gel-fill-in'),
  ('team-member-13', 'gel-full-set'),
  ('team-member-13', 'gel-fill-in'),
  ('team-member-13', 'dip-powder'),
  ('team-member-13', 'dip-with-tips'),
  ('team-member-13', 'manicure'),
  ('team-member-13', 'deluxe-manicure'),
  ('team-member-13', 'deluxe-pedicure'),
  ('team-member-13', 'jelly-pedicure'),
  ('team-member-13', 'royal-pedicure'),
  ('team-member-13', 'ultimate-pedicure'),
  ('team-member-13', 'kids-regular-polish'),
  ('team-member-14', 'acrylic-full-set'),
  ('team-member-14', 'acrylic-fill-in'),
  ('team-member-14', 'poly-gel-full-set'),
  ('team-member-14', 'poly-gel-fill-in'),
  ('team-member-14', 'gel-full-set'),
  ('team-member-14', 'gel-fill-in'),
  ('team-member-14', 'dip-powder'),
  ('team-member-14', 'dip-with-tips'),
  ('team-member-14', 'manicure'),
  ('team-member-14', 'deluxe-manicure'),
  ('team-member-14', 'deluxe-pedicure'),
  ('team-member-14', 'jelly-pedicure'),
  ('team-member-14', 'royal-pedicure'),
  ('team-member-14', 'ultimate-pedicure'),
  ('team-member-14', 'kids-regular-polish'),
  ('team-member-15', 'acrylic-full-set'),
  ('team-member-15', 'acrylic-fill-in'),
  ('team-member-15', 'poly-gel-full-set'),
  ('team-member-15', 'poly-gel-fill-in'),
  ('team-member-15', 'gel-full-set'),
  ('team-member-15', 'gel-fill-in'),
  ('team-member-15', 'dip-powder'),
  ('team-member-15', 'dip-with-tips'),
  ('team-member-15', 'manicure'),
  ('team-member-15', 'deluxe-manicure'),
  ('team-member-15', 'deluxe-pedicure'),
  ('team-member-15', 'jelly-pedicure'),
  ('team-member-15', 'royal-pedicure'),
  ('team-member-15', 'ultimate-pedicure'),
  ('team-member-15', 'kids-regular-polish'),
  ('team-member-16', 'acrylic-full-set'),
  ('team-member-16', 'acrylic-fill-in'),
  ('team-member-16', 'poly-gel-full-set'),
  ('team-member-16', 'poly-gel-fill-in'),
  ('team-member-16', 'gel-full-set'),
  ('team-member-16', 'gel-fill-in'),
  ('team-member-16', 'dip-powder'),
  ('team-member-16', 'dip-with-tips'),
  ('team-member-16', 'manicure'),
  ('team-member-16', 'deluxe-manicure'),
  ('team-member-16', 'deluxe-pedicure'),
  ('team-member-16', 'jelly-pedicure'),
  ('team-member-16', 'royal-pedicure'),
  ('team-member-16', 'ultimate-pedicure'),
  ('team-member-16', 'kids-regular-polish'),
  ('team-member-17', 'acrylic-full-set'),
  ('team-member-17', 'acrylic-fill-in'),
  ('team-member-17', 'poly-gel-full-set'),
  ('team-member-17', 'poly-gel-fill-in'),
  ('team-member-17', 'gel-full-set'),
  ('team-member-17', 'gel-fill-in'),
  ('team-member-17', 'dip-powder'),
  ('team-member-17', 'dip-with-tips'),
  ('team-member-17', 'manicure'),
  ('team-member-17', 'deluxe-manicure'),
  ('team-member-17', 'deluxe-pedicure'),
  ('team-member-17', 'jelly-pedicure'),
  ('team-member-17', 'royal-pedicure'),
  ('team-member-17', 'ultimate-pedicure'),
  ('team-member-17', 'kids-regular-polish'),
  ('team-member-18', 'cut-with-wash'),
  ('team-member-18', 'cut-without-wash'),
  ('team-member-18', 'buzz-cut'),
  ('team-member-18', 'bang-trim'),
  ('team-member-18', 'conditioning-treatment'),
  ('team-member-18', 'roller-set'),
  ('team-member-18', 'blowout'),
  ('team-member-18', 'style'),
  ('team-member-18', 'updo'),
  ('team-member-18', 'spiral-perm'),
  ('team-member-18', 'partial-perm'),
  ('team-member-18', 'full-color'),
  ('team-member-18', 'full-highlights'),
  ('team-member-18', 'balayage'),
  ('team-member-18', 'money-piece'),
  ('team-member-18', 'partial-color'),
  ('team-member-18', 'partial-highlights'),
  ('team-member-18', 'root-touch-up'),
  ('team-member-19', 'tattoo-consult'),
  ('team-member-19', 'flash-tattoo'),
  ('team-member-21', 'acrylic-full-set'),
  ('team-member-21', 'acrylic-fill-in'),
  ('team-member-21', 'poly-gel-full-set'),
  ('team-member-21', 'poly-gel-fill-in'),
  ('team-member-21', 'gel-full-set'),
  ('team-member-21', 'gel-fill-in'),
  ('team-member-21', 'dip-powder'),
  ('team-member-21', 'dip-with-tips'),
  ('team-member-21', 'manicure'),
  ('team-member-21', 'deluxe-manicure'),
  ('team-member-21', 'deluxe-pedicure'),
  ('team-member-21', 'jelly-pedicure'),
  ('team-member-21', 'royal-pedicure'),
  ('team-member-21', 'ultimate-pedicure'),
  ('team-member-21', 'kids-regular-polish')
) as map(staff_slug, service_slug)
join public.staff_members staff on staff.slug=map.staff_slug
join public.services service on service.slug=map.service_slug
on conflict do nothing;

select pg_notify('pgrst', 'reload schema');
